### PR TITLE
Return original value when no image or not safe

### PR DESCRIPTION
**Pull request by boboldehampsink**
An example of usage is when you don't want to transform SVG images at all. If you keep SVG out of the safe file formats, it won't touch them but still return the original SVG.

### CODE REVIEW

**Comment by boboldehampsink** [comment]
An example of usage is when you don't want to transform SVG images at all. If you keep SVG out of the safe file formats, it won't touch them but still return the original SVG.

**Comment by boboldehampsink** [comment]
@aelvan I understand. Just looking for a solution that works with https://craftcms.com/docs/4.x/config/general.html#transformsvgs - maybe you have a better idea?

**Comment by aelvan** [comment]
Well, the gist of `transformSvgs` is covered by `safeFileFormats` in Imager; if SVG is listed there, it will be transformed, if not, it wont. But, what you're getting at is maybe that `asset.getUrl({ width:200 })` in twig, on a svg, with `transformSvgs` disabled, will return the original assets url?

As I wrote, I'm thinking that it's better to handle this in the application that gets the data. Just returning the original url for the asset together with the transformed url, and then doing a conditional that falls back on the original if it couldn't be transformed.

In addition to feeling a bit iffy, this change would break backwards compatibility for anyone relying on the directives returning `null` if the file can't be transformed. Which I suspect could be quite disruptive (ie non-image files being used as images).

**Comment by boboldehampsink** [comment]
Ok thanks, added this in my FE.

**Pull request closed without merging**
