### PR TITLE
Only delete local transforms when not using imgix

### PR DESCRIPTION
**Pull request by boboldehampsink**
When using Imgix there are no local transforms anyway. Now it keeps throwing errors because it wants to remove images that are not there.

This is an attempt to fix that.

### CODE REVIEW

**Comment by aelvan** [comment]
Hi @boboldehampsink !

Thanks for submitting the PR. I'm not able to reproduce any errors related to this. What is the error and can you shed some light on what circumstances it might occur under? I probably need to implement a different solution here to account for  custom transformers.

**Comment by boboldehampsink** [comment]
@aelvan it might occur specifically when using multiple server nodes, so the local file isn't always there.

**Comment by aelvan** [comment]
Even if I remove the whole imagerSystemPath folder I don't get any errors in that call. But maybe it's because you don't have a traditional file system? What type of server setup are you experiencing this on? You wouldn't happen to have the actual error message/stack trace?

**Comment by boboldehampsink** [comment]
This is the error:

`spacecatninja\imagerx\services\ImagerService::removeTransformsForAsset`
```
Could not clear directory "/app/web/imager/objects/hezingen-schabosweg-3/82313" (The dir argument must be a directory: /app/web/imager/objects/hezingen-schabosweg-3/82313)
```

**Comment by aelvan** [comment]
Right. Any chance you could try another potential fix for me?

**Comment by boboldehampsink** [comment]
@aelvan sure

**Comment by aelvan** [comment]
Great, thanks! 

Inside `removeTransformsForAsset`, could you try surrounding the try/catch block staring on line 573, ie:

```
try {
    FileHelper::clearDirectory(FileHelper::normalizePath($targetModel->path));
    FileHelper::removeDirectory(FileHelper::normalizePath($targetModel->path));
} catch (ErrorException $e) {
    Craft::error('Could not clear directory "' . $targetModel->path . '" (' . $e->getMessage() . ')', __METHOD__);
} catch (InvalidArgumentException $e) {
    Craft::error('Could not clear directory "' . $targetModel->path . '" (' . $e->getMessage() . ')', __METHOD__);
}
```

With this conditional:

```
if (file_exists($targetModel->path)) {
...
}
```

And of course reverting the change you did where this is not run if you're using the Imgix transform.

**Comment by boboldehampsink** [comment]
@aelvan I used `is_dir` instead of `file_exists`, and added it on all occurences of `clearDirectory`

**Comment by aelvan** [comment]
And this fixed your issue?

**Comment by boboldehampsink** [comment]
Yes, running this fix in production. So far so good, no errors.

**Comment by aelvan** [comment]
Great, merging!

**Pull request merged**
